### ISSUE TITLE
Docker images compatible with Pi4 

### ISSUE THREAD

**Issue by dash82** [victronenergy/venus-docker-grafana-images#11]
Love the flexibility of being able to run grafana with my victron setup, recently bought a pi4 to move my monitoring off my main pc.. only to find the images don't support pi4 yet... Would be great if this would be added to the compatible architectures.

**Comment by robtor-de** [comment]
Why don't they work? I have a pi4 running for a few months with the server docker image?
Or do you use the 64-Bit experimental installation of raspbian?

**Comment by dash82** [comment]
I am using ubuntu 20.04 on the Pi4. Most of my other dockers work, but not the Victron images docker unfortunately.

ubuntu@pi1:~/dockers/victron$ docker-compose up -d
Pulling server (victronenergy/venus-docker-server:latest)...
latest: Pulling from victronenergy/venus-docker-server
ERROR: no matching manifest for linux/arm64/v8 in the manifest list entries
ubuntu@pi1:~/dockers/victron$ uname -a
Linux pi1 5.4.0-1018-raspi #20-Ubuntu SMP Sun Sep 6 05:11:16 UTC 2020 aarch64 aarch64 aarch64 GNU/Linux

**Comment by robtor-de** [comment]
I think the reason why it works with my Pi is that I have raspian with armhf architecture installed, and you are using ubuntu with aarch64

**Comment by jarrettj** [comment]
Any solution to this one? Workaround that does not involve an OS reinstall :).

**Comment by dash82** [comment]
> Any solution to this one? Workaround that does not involve an OS reinstall :).

I tried with the 64bit pi install, same thing... did it so i could run the pi4 off usb ssd... But last time i checked this was still an issue.. Have the other dockers running on my pc, and then grafana on my pi4... thats my work around for now.. But maybe 32bit will work... i haven't tried that yet..

**Comment by jarrettj** [comment]
32 bit works fine. Found out that I can send the data directly to home assistant via modbus. So that’s fine for me. No need for the fancy graphing right now.

________________________________

**Comment by mpvader** [comment]
Hi, I'm no docker expert, and at the moment me nor any of the other colleagues has time to look into this, but I'd think you can compile a version for your architecture yourself, no?

Its all open source, no closed sources involved.

**Comment by Knobee** [comment]
see https://github.com/victronenergy/venus-docker-grafana-images/issues/12

**Comment by mman** [comment]
Issue will be addressed in the https://github.com/victronenergy/venus-influx-loader repo, closing here. Feel free to reopen there if you see any issues.
