### ISSUE TITLE
No linux/arm docker package available? 

### ISSUE THREAD

**Issue by stormmurdoc** [victronenergy/venus-docker-grafana-images#12]
At the moment, the victron grafana container does not run on an arm architecture. Since version 2.0.0 was already available for this platform, why are there no arm packages?

**Comment by mpvader** [comment]
Hi, thats because on our side we’re currently not actively developping this. There is noone around with time at the moment.

You’re welcome to send in a pull request though!

and most likely you can build any package you want yourself from source, as well. Or not? (I’m not too familiar with the process yet)

**Comment by Knobee** [comment]
This can be solved by cloning the repo on a Pi4 and running a "docker build" in the `grafana` directory.

`
aclegg@display:~ $ cd Victron/
aclegg@display:~/Victron $ cd venus-docker-grafana-images/
aclegg@display:~/Victron/venus-docker-grafana-images $ ls
grafana  LICENSE  README.md  server
aclegg@display:~/Victron/venus-docker-grafana-images $ cd grafana/
aclegg@display:~/Victron/venus-docker-grafana-images/grafana $ ls
build-images.sh  Dockerfile  entrypoint.sh  initial
aclegg@display:~/Victron/venus-docker-grafana-images/grafana $ docker build `pwd`
Sending build context to Docker daemon  792.1kB
Step 1/6 : FROM grafana/grafana
 ---> 446e136d475e
Step 2/6 : COPY initial /initial
 ---> Using cache
 ---> c01d88a76cd8
Step 3/6 : COPY entrypoint.sh /
 ---> Using cache
 ---> c9521855f362
Step 4/6 : ARG GF_INSTALL_PLUGINS="simpod-json-datasource"
 ---> Using cache
 ---> 4eb9904887a6
Step 5/6 : RUN if [ ! -z "${GF_INSTALL_PLUGINS}" ]; then     OLDIFS=$IFS;         IFS=',';     for plugin in ${GF_INSTALL_PLUGINS}; do         IFS=$OLDIFS;         grafana-cli --pluginsDir "$GF_PATHS_PLUGINS" plugins install ${plugin};     done; fi
 ---> Using cache
 ---> e5927ac0fa46
Step 6/6 : ENTRYPOINT ["/entrypoint.sh"]
 ---> Using cache
 ---> a108229c9c96
Successfully built a108229c9c96
`

You can then run the docker image that was built.

Someone with appropriate privileges could run:

`
aclegg@display:~/Victron/venus-docker-grafana-images/grafana $ ./build-images.sh linux arm
Sending build context to Docker daemon  792.1kB
Step 1/6 : FROM grafana/grafana
 ---> 446e136d475e
Step 2/6 : COPY initial /initial
 ---> fc5ce909fa1e
Step 3/6 : COPY entrypoint.sh /
 ---> 6a2e96440638
Step 4/6 : ARG GF_INSTALL_PLUGINS="simpod-json-datasource"
 ---> Running in 6d9e90580311
Removing intermediate container 6d9e90580311
 ---> 0d6dde7e88bb
Step 5/6 : RUN if [ ! -z "${GF_INSTALL_PLUGINS}" ]; then     OLDIFS=$IFS;         IFS=',';     for plugin in ${GF_INSTALL_PLUGINS}; do         IFS=$OLDIFS;         grafana-cli --pluginsDir "$GF_PATHS_PLUGINS" plugins install ${plugin};     done; fi
 ---> Running in f9571693f74e
installing simpod-json-datasource @ 0.2.4
from: https://grafana.com/api/plugins/simpod-json-datasource/versions/0.2.4/download
into: /var/lib/grafana/plugins

✔ Installed simpod-json-datasource successfully

Restart grafana after installing plugins . <service grafana-server restart>

Removing intermediate container f9571693f74e
 ---> 3f18bfd374bb
Step 6/6 : ENTRYPOINT ["/entrypoint.sh"]
 ---> Running in e35a07f5d9a8
Removing intermediate container e35a07f5d9a8
 ---> ea88f072d82c
Successfully built ea88f072d82c
Successfully tagged victronenergy/venus-docker-grafana:linux-arm
The push refers to repository [docker.io/victronenergy/venus-docker-grafana]
71cda14eb341: Preparing
871e650fbe7a: Preparing
360fd82c18ff: Preparing
04b9e75057fe: Preparing
5517431aa9b4: Preparing
5f70bf18a086: Waiting
67d782e60cd9: Waiting
388bf28e822b: Waiting
b797dbfa1439: Waiting
a8925b2335ff: Waiting
denied: requested access to the resource is denied
no such manifest: docker.io/victronenergy/venus-docker-grafana:armhf-arm
No such manifest: docker.io/victronenergy/venus-docker-grafana:arm
`

**Comment by Knobee** [comment]
My attempted edits of the above text to get it formatted correctly are going nowhere so I'll give up on that now.  :-)

**Comment by Knobee** [comment]
last note -- the above has allowed me to get the docker image running on my RPi 4 by modifying the docker-compose.yaml in the other project to include:

`  graphing:
#    image: "victronenergy/venus-docker-grafana:latest"
    image: "a108229c9c96"
    volumes:
     - "grafana-storage:/var/lib/grafana"
    ports:
     - "3000:3000"`

**Comment by mman** [comment]
Issue will be addressed in the https://github.com/victronenergy/venus-influx-loader repo, closing here. Feel free to reopen there if you see any issues.
