### ISSUE TITLE
Server to support influx authentization

### ISSUE THREAD

**Issue by LukasVyhlidka** [victronenergy/venus-docker-grafana-images#14]
Hi, I have tried the venus server to connect to my own Influx DB. But unfortunately, my influx uses the authentication. I tackle that by changing the source code directly in the docker container (thanks its not compiled) a little bit so it can read username and password from /config config file. For my purposes I do not need to have the UI configuration so the config file is just fine :)

Would you accept PR so it gets to the official docker image?

**Comment by LukasVyhlidka** [comment]
Corresponding PR: https://github.com/victronenergy/venus-docker-grafana-images/pull/15

**Comment by cernoch** [comment]
I'd love to see this merged as well.

**Comment by LukasVyhlidka** [comment]
Until then, you can just replace the file from PR in your installation as I did.

If used in docker, you can use `docker cp` / `docker exec ..... sh` for it.

**Comment by mman** [comment]
Issue addressed in the https://github.com/victronenergy/venus-influx-loader repo, closing here. Feel free to reopen there if you see any issues.
