### ISSUE TITLE
feature request: prometheus exporter 

### ISSUE THREAD

**Issue by Beuk1989** [victronenergy/venus-docker-grafana-images#23]
can you make the data available as prometheus Exporter?

**Comment by mman** [comment]
@Beuk1989 How would you like it to work please? Prometheus typically works the other way around. So it is polling the data source - in our case the data source would be Venus OS running on an IP and exposing all the metrics.

do I understand it right?
Martin

**Comment by Beuk1989** [comment]
i'm not very familiar with node.js.  but maybe it is possible that the data from the mqtt is held with a timestamp and then the data in prometheus format can be retrieved with remote_read or with a common exporter or JSON_exporter

**Comment by mman** [comment]
@Beuk1989 The influxdb exporter looks like something that should work. Note that in default config provided by Victron (https://github.com/victronenergy/venus-docker-grafana/blob/master/docker-compose.yaml) the influxdb container actually runs isolated from the outer network so it can not be connected to from the outside. But you can actually run influxdb_exporter as a separate docker container referenced from that same `docker-compose.yaml`. That way the influxdb_exporter will get access to influx. Or you can run influxdb container in `network_mode: host` the same as the `upnp` container.

I strongly believe this is doable and it's just a matter of proper setup... Do you have your `docker-compose.yaml` to share? I will suggest changes...

**Comment by mman** [comment]
@Beuk1989 I tried quickly today and I am getting the same error. It happens when the `venus-grafana-server` tries to fetch list of databases in influx here https://github.com/victronenergy/venus-docker-grafana-images/blob/4dafdc0b0635f2f5de498895f0efd841955338a8/server/lib/influxdb.js#L104 and fails.

Not sure what can be done about this. Influx 1 is officially dead, Influx 2 is not (yet if ever) supported by prometheus exporter, so the question is why you need Prometheus at all? Why not talk to Influx directly?

**Comment by mman** [comment]
@Beuk1989 I did investigate this a bit more and here is what I found:

First thing an InfluxDB client does is to get back list of existing databases:

It posts the HTTP query:

```
GET /query?q=show%20databases
```

And [influxdb_exporter](https://github.com/prometheus/influxdb_exporter) returns back an empty array:

```
{
  results: []
}
```

This comes from here: https://github.com/prometheus/influxdb_exporter/blob/82a5c587be7de4a447763af33cdbc8ffc597ef78/main.go#L366

When the same request is fired against [InfluxDB 1.8](https://hub.docker.com/layers/library/influxdb/1.8/images/sha256-da86d34e0b672d344fbccf6b52c41996b38c50d76565acd102a773fc66f10d2a?context=explore) this is what comes back.

```
{
  "results": [
    {
      "statement_ id": 0,
      "series": [
        {
          "name": "databas es",
          "columns": [
            " name"
          ]
        }
      ]
    }
  ]
}
```

So real Influx DB actually returns one row, which I think is what the InfluxDB client expects.

Venus Grafana Server currently uses the (now deprecated) https://www.npmjs.com/package/influx node js module.

This repo should probably move to the official https://www.npmjs.com/package/@influxdata/influxdb-client that supports Influx DB 1.8+ as well as Influx DB 2.

After the upgrade the problem may go away.

**Comment by Beuk1989** [comment]
thanks for your comment.  
I now have InfluxDB 1.7 running.  I was actually already using version 2+.  but this is good for now.  

I have one other small question. 
is it possible to refresh the VRM name list with a cron job via /admin-api/refreshVRM.  we regularly use other names because the sets are rented out.  then I can update the names automatically in Grafana.

**Comment by mman** [comment]
@Beuk1989 sorry for my late reply, been busy updating the code.

You should be able to actually do this easily yourself, for example by overriding `HEALTHCHECK` command for your Venus Grafana Server container to use `curl -X PUT http://localhost:8088/admin-api/refreshVRM`. There are even params how often to do this.

Look for `healthcheck`   here: https://docs.docker.com/compose/compose-file/compose-file-v3/

**Comment by Beuk1989** [comment]
Yesterday I made a cronjob on the host.  which sends a curl put request to the docker port 8088. this seems to work.  once a day the server refreshes the VRM instance names.  I will also take a look at the healthcheck method.

**Comment by mpvader** [comment]
Hey @Beuk1989 can I get in touch with you somehow?

**Comment by Beuk1989** [comment]
I have sent you an email if I found the right one

**Comment by mman** [comment]
Closing the issue as there is no plan to address this at the moment. Feel free to re-open against https://github.com/victronenergy/venus-influx-loader repo where the Venus Grafana work continues.
